- name: configure kafka file
  template: 
    src: server.properties.j2
    dest: /usr/local/kafka/config/server.properties
    owner: "kafka"
    group: "kafka"
  notify:
    restart kafka


- name: set jmx 
  lineinfile:
    dest: /usr/local/kafka/bin/kafka-server-start.sh 
    regexp: '^export KAFKA_HEAP_OPTS'
    insertafter: 'export KAFKA_HEAP_OPTS'
    line: 'export JMX_PORT="9999"'
