- name: add redis group
  group: name=redis
- name: add redis user 
  user: name=redis groups=redis shell=/sbin/nologin

- name: copy redis-5.0.5.tar.gz 
  copy: src=redis-5.0.5.tar.gz dest=/usr/local/src/
- name: unarchive redis-5.0.5.tar.gz
  unarchive: src=/usr/local/src/redis-5.0.5.tar.gz dest=/usr/local/ copy=no owner=redis group=redis

- name: Create symlink redis home dir
  file: 
    path: /usr/local/redis
    src: /usr/local/redis-5.0.5
    state: link
    owner: redis
    group: redis



- name: install redis
  shell: cd /usr/local/redis && make && make install

- name: create redis data dir 
  file: 
    path: /var/lib/redis
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: create redis log dir 
  file: 
    path: /var/log/redis
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: create soft link for configure file
  file:
    src: /usr/local/redis/redis.conf 
    dest: /etc/redis.conf
    state: link
- name: add redis to system service
  template: src=redis-server.service.j2 dest=/etc/systemd/system/redis-server.service 

