- name: install mongo
  include: install.yml


- name: configure file
  include: configure.yml


- include_tasks: service.yml

- name: create user
  include: auth_initialization.yml


- name: init replicaSet
  include: init_replicaset.yml
  when: (MONGO_MASTER is defined and MONGO_MASTER)

