- name: create redis-sentinel data dir 
  file: 
    path: /var/lib/redis-sentinel
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: copy sentinel.conf.j2
  template: src=sentinel.conf.j2 dest=/usr/local/redis/redis-sentinel.conf

- name: create soft link for redis-sentinel configure file
  file:
    src: /usr/local/redis/redis-sentinel.conf 
    dest: /etc/redis-sentinel.conf
    state: link
    owner: redis
    group: redis

- name: add sentinel to system service
  template: src=redis-sentinel.service.j2 dest=/etc/systemd/system/redis-sentinel.service

- name: restart redis-sentinel server
  service: name=redis-sentinel state=restarted enabled=yes

