- name: config host
  blockinfile:
    path: /etc/hosts
    block: "{{ rabbitmq_hosts }}"
    owner: root
    group: root
    mode: 0644

- name: check if esl-erlang is installed
  command: dpkg-query -W esl-erlang
  register: erlang_pkg_check
  ignore_errors: yes
  changed_when: false


- name: install depenency pakages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - socat
    - libncurses5
    - libwxgtk3.0-dev
    - libwxbase3.0-0v5

- name: copy pakages to mq hosts
  copy: 
    src: "{{item.src}}"
    dest: /usr/local/src/
  with_items:
    - { src: 'esl-erlang_21.3.8.7-1_debian_buster_amd64.deb'}
    - { src: 'rabbitmq-server_3.7.18-1_all.deb' }

- name: install esl-erlang and rabbitmq-server pkg
  apt:
    deb: "{{ item }}"
  with_items:
    - /usr/local/src/esl-erlang_21.3.8.7-1_debian_buster_amd64.deb
    - /usr/local/src/rabbitmq-server_3.7.18-1_all.deb

- name: install rabbitm-server
  apt:
    update_cache: yes
    force: yes
    pkg: "{{item}}"
    state: present
  with_items:
    - rabbitmq-server

- name: create rabbitmq data and log dir
  file:
    path: "{{ item }}"
    state: directory
    owner: rabbitmq
    group: rabbitmq
  with_items:
    - /mnt/lv01/rabbitmq/mnesia
    - /mnt/lv01/rabbitmq/log

- include_tasks: erlang_cookie.yml
  when: rabbitmq_create_cluster

- include_tasks: config.yml
  

- include_tasks: service.yml

- include_tasks: cluster.yml
  when: rabbitmq_create_cluster == true
